import express from 'express';
import { createChatroom, getChatroomDatabyChatroomId, getChatroomDatabyCreatorId, joinChatroom, getChatrooms} from '../controllers/chatrooms.controller';
import { authMiddleware } from '../middleware/auth.middleware';
const router = express.Router();
router.post('/create-chatroom', authMiddleware, createChatroom);
router.post('/get-chatroomdatabyChatroomid/:id', authMiddleware, getChatroomDatabyChatroomId);
router.post('/get-chatroomdatabyCreatorid', authMiddleware, getChatroomDatabyCreatorId);
router.post('/join-chatroom/:id', authMiddleware, joinChatroom);
router.post('/get-chatrooms', authMiddleware, getChatrooms);
export default router;